// Auto-generated by scripts/build-icons.ts
import { CheckIcon, ChevronDownIcon, ChevronRightIcon, SearchIcon, XIcon } from "lucide-solid"

const icons = { CheckIcon, ChevronDownIcon, ChevronRightIcon, SearchIcon, XIcon }

export default icons
