// Auto-generated by scripts/build-icons.ts
import { CheckIcon, ChevronDownIcon, ChevronRightIcon } from "lucide-solid"

const icons = { CheckIcon, ChevronDownIcon, ChevronRightIcon }

export default icons
