// Auto-generated by scripts/build-icons.ts
import {
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  Ellipsis,
  LoaderCircleIcon,
  Minus,
  MinusIcon,
  MoreHorizontalIcon,
  PanelLeftIcon,
  SearchIcon,
  XIcon
} from "lucide-solid"

const icons = {
  CheckIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronsUpDownIcon,
  Ellipsis,
  LoaderCircleIcon,
  Minus,
  MinusIcon,
  MoreHorizontalIcon,
  PanelLeftIcon,
  SearchIcon,
  XIcon
}

export default icons
