// Auto-generated by scripts/build-icons.ts
import { IconCheck, IconChevronDown, IconChevronRight } from "@tabler/icons-solidjs"

const icons = { IconCheck, IconChevronDown, IconChevronRight }

export default icons
