// Auto-generated by scripts/build-icons.ts
import {
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconSearch,
  IconX
} from "@tabler/icons-solidjs"

const icons = { IconCheck, IconChevronDown, IconChevronRight, IconSearch, IconX }

export default icons
