// Auto-generated by scripts/build-icons.ts
import {
  IconAlertOctagon,
  IconAlertTriangle,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDots,
  IconInfoCircle,
  IconLayoutSidebar,
  IconLoader,
  IconMinus,
  IconSearch,
  IconTrendingDown,
  IconTrendingUp,
  IconWallet,
  IconX
} from "@tabler/icons-solidjs"

const icons = {
  IconAlertOctagon,
  IconAlertTriangle,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconCircleCheck,
  IconDeviceDesktop,
  IconDeviceMobile,
  IconDots,
  IconInfoCircle,
  IconLayoutSidebar,
  IconLoader,
  IconMinus,
  IconSearch,
  IconTrendingDown,
  IconTrendingUp,
  IconWallet,
  IconX
}

export default icons
