#!/usr/bin/env tsx
import * as fs from "node:fs"
import * as path from "node:path"

import ts from "typescript"

import { type IconLibraryName, iconLibraries } from "~/registry/icon-libraries"

type IconUsage = Record<IconLibraryName, Set<string>>

function findTsxFiles(dir: string) {
  const files: string[] = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...findTsxFiles(fullPath))
    } else if (entry.isFile() && entry.name.endsWith(".tsx")) {
      files.push(fullPath)
    }
  }

  return files
}

function scanIconUsage() {
  const iconUsage: IconUsage = Object.keys(iconLibraries).reduce((acc, key) => {
    acc[key as IconLibraryName] = new Set()
    return acc
  }, {} as IconUsage)

  const registryBasesDir = path.join(process.cwd(), "src/registry")
  const files = findTsxFiles(registryBasesDir)
  const libraryNames = Object.values(iconLibraries)
    .map((lib) => lib.name)
    .join("|")
  const iconPlaceholderRegex = new RegExp(
    `<IconPlaceholder\\s+([^>]*?)(?:${libraryNames})=["']([^"']+)["']([^>]*?)\\/?>`,
    "g"
  )

  for (const file of files) {
    const content = fs.readFileSync(file, "utf-8")

    let match: RegExpExecArray | null = null
    while (true) {
      match = iconPlaceholderRegex.exec(content)
      if (!match) {
        break
      }

      const fullMatch = match[0]

      for (const [libraryName, config] of Object.entries(iconLibraries)) {
        const attrMatch = fullMatch.match(new RegExp(`${config.name}=["']([^"']+)["']`))
        const iconName = attrMatch?.[1]
        if (iconName) {
          iconUsage[libraryName as IconLibraryName].add(iconName)
        }
      }
    }
  }

  // temporary
  mergePickerPreviewIconUsage(iconUsage)

  return iconUsage
}

function getPropertyName(name: ts.PropertyName) {
  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
    return name.text
  }

  return undefined
}

function mergePickerPreviewIconUsage(iconUsage: IconUsage) {
  const pickerFile = path.join(process.cwd(), "src/components/icon-library-picker.tsx")

  if (!fs.existsSync(pickerFile)) {
    return
  }

  const content = fs.readFileSync(pickerFile, "utf-8")
  const source = ts.createSourceFile(
    pickerFile,
    content,
    ts.ScriptTarget.Latest,
    true,
    ts.ScriptKind.TSX
  )

  const visit = (node: ts.Node) => {
    if (
      ts.isVariableDeclaration(node) &&
      ts.isIdentifier(node.name) &&
      node.name.text === "PREVIEW_ICONS" &&
      node.initializer &&
      ts.isObjectLiteralExpression(node.initializer)
    ) {
      for (const property of node.initializer.properties) {
        if (!ts.isPropertyAssignment(property)) {
          continue
        }

        const libraryName = getPropertyName(property.name)
        if (!libraryName || !(libraryName in iconLibraries)) {
          continue
        }

        if (!ts.isArrayLiteralExpression(property.initializer)) {
          continue
        }

        const usage = iconUsage[libraryName as IconLibraryName]
        for (const element of property.initializer.elements) {
          if (ts.isStringLiteralLike(element)) {
            usage.add(element.text)
          }
        }
      }
    }

    ts.forEachChild(node, visit)
  }

  visit(source)
}

function generateIconFiles(iconUsage: IconUsage) {
  const outputDir = path.join(process.cwd(), "src/registry/icons")

  console.log("✓ Generated icon files:")

  Object.entries(iconLibraries).forEach(([libraryName, config]) => {
    const icons = Array.from(iconUsage[libraryName as IconLibraryName]).sort()

    if (icons.length === 0) {
      return
    }

    const content = `// Auto-generated by scripts/build-icons.ts
${icons.map((icon) => `export { ${icon} } from "${config.export}"`).join("\n")}
`

    const filename = `__${libraryName}__.ts`
    fs.writeFileSync(path.join(outputDir, filename), content)

    console.log(`  - ${config.title}: ${icons.length} icons`)
  })
}

function main() {
  const iconUsage = scanIconUsage()
  generateIconFiles(iconUsage)
}

const isWatchMode = process.argv.includes("--watch")

if (isWatchMode) {
  const REGISTRY_DIR = path.join(process.cwd(), "src/registry")
  const ICON_LIBRARY_PICKER_FILE = path.join(
    process.cwd(),
    "src/components/icon-library-picker.tsx"
  )

  async function startWatcher() {
    const { default: chokidar } = await import("chokidar")

    main()

    const watcher = chokidar.watch([REGISTRY_DIR, ICON_LIBRARY_PICKER_FILE], {
      ignored: /(^|[/\\])\../,
      persistent: true,
      ignoreInitial: true
    })

    const rebuild = (filename: string) => {
      if (!filename.endsWith(".tsx")) return

      try {
        main()
      } catch (error) {
        console.error("❌ Icons build failed:", error)
      }
    }

    watcher.on("error", (error) => {
      console.error("❌ Watcher error:", error)
    })

    watcher.on("change", rebuild)
    watcher.on("add", rebuild)

    process.on("SIGINT", async () => {
      await watcher.close()
      process.exit(0)
    })
  }

  startWatcher()
} else {
  main()
}
