// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/lib/utils.ts")),
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "accordion": {
    name: "accordion",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/accordion.tsx")),
    files: [{
      path: "registry/ui/accordion.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/button.tsx")),
    files: [{
      path: "registry/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "collapsible": {
    name: "collapsible",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/collapsible.tsx")),
    files: [{
      path: "registry/ui/collapsible.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "separator": {
    name: "separator",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/separator.tsx")),
    files: [{
      path: "registry/ui/separator.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/tabs.tsx")),
    files: [{
      path: "registry/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "accordion-demo": {
    name: "accordion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    component: lazy(() => import("~/registry/examples/accordion-demo.tsx")),
    files: [{
      path: "registry/examples/accordion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/hooks/use-mobile.ts")),
    files: [{
      path: "registry/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
}
