// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import { lazy } from "solid-js"

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/lib/utils.ts")),
    files: [{
      path: "registry/lib/utils.ts",
      type: "registry:lib",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "accordion": {
    name: "accordion",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/accordion.tsx")),
    files: [{
      path: "registry/ui/accordion.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button": {
    name: "button",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/button.tsx")),
    files: [{
      path: "registry/ui/button.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group": {
    name: "button-group",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/button-group.tsx")),
    files: [{
      path: "registry/ui/button-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "card": {
    name: "card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/card.tsx")),
    files: [{
      path: "registry/ui/card.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command": {
    name: "command",
    description: "",
    type: "registry:ui",
    registryDependencies: ["dialog","input-group"],
    component: lazy(() => import("~/registry/ui/command.tsx")),
    files: [{
      path: "registry/ui/command.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "collapsible": {
    name: "collapsible",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/collapsible.tsx")),
    files: [{
      path: "registry/ui/collapsible.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox": {
    name: "combobox",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","input-group"],
    component: lazy(() => import("~/registry/ui/combobox.tsx")),
    files: [{
      path: "registry/ui/combobox.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dialog": {
    name: "dialog",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/ui/dialog.tsx")),
    files: [{
      path: "registry/ui/dialog.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "dropdown-menu": {
    name: "dropdown-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/dropdown-menu.tsx")),
    files: [{
      path: "registry/ui/dropdown-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "hover-card": {
    name: "hover-card",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/hover-card.tsx")),
    files: [{
      path: "registry/ui/hover-card.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input": {
    name: "input",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/input.tsx")),
    files: [{
      path: "registry/ui/input.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group": {
    name: "input-group",
    description: "",
    type: "registry:ui",
    registryDependencies: ["button","input","textarea"],
    component: lazy(() => import("~/registry/ui/input-group.tsx")),
    files: [{
      path: "registry/ui/input-group.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "label": {
    name: "label",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/label.tsx")),
    files: [{
      path: "registry/ui/label.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "navigation-menu": {
    name: "navigation-menu",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/navigation-menu.tsx")),
    files: [{
      path: "registry/ui/navigation-menu.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "popover": {
    name: "popover",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/popover.tsx")),
    files: [{
      path: "registry/ui/popover.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "separator": {
    name: "separator",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/separator.tsx")),
    files: [{
      path: "registry/ui/separator.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tabs": {
    name: "tabs",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/tabs.tsx")),
    files: [{
      path: "registry/ui/tabs.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "tooltip": {
    name: "tooltip",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/tooltip.tsx")),
    files: [{
      path: "registry/ui/tooltip.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "textarea": {
    name: "textarea",
    description: "",
    type: "registry:ui",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/ui/textarea.tsx")),
    files: [{
      path: "registry/ui/textarea.tsx",
      type: "registry:ui",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "accordion-demo": {
    name: "accordion-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["accordion"],
    component: lazy(() => import("~/registry/examples/accordion-demo.tsx")),
    files: [{
      path: "registry/examples/accordion-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-demo": {
    name: "button-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-demo.tsx")),
    files: [{
      path: "registry/examples/button-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-size": {
    name: "button-size",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-size.tsx")),
    files: [{
      path: "registry/examples/button-size.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-default": {
    name: "button-default",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-default.tsx")),
    files: [{
      path: "registry/examples/button-default.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-outline": {
    name: "button-outline",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-outline.tsx")),
    files: [{
      path: "registry/examples/button-outline.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-secondary": {
    name: "button-secondary",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-secondary.tsx")),
    files: [{
      path: "registry/examples/button-secondary.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-ghost": {
    name: "button-ghost",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-ghost.tsx")),
    files: [{
      path: "registry/examples/button-ghost.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-destructive": {
    name: "button-destructive",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-destructive.tsx")),
    files: [{
      path: "registry/examples/button-destructive.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-link": {
    name: "button-link",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-link.tsx")),
    files: [{
      path: "registry/examples/button-link.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-icon": {
    name: "button-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-icon.tsx")),
    files: [{
      path: "registry/examples/button-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-with-icon": {
    name: "button-with-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-with-icon.tsx")),
    files: [{
      path: "registry/examples/button-with-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-rounded": {
    name: "button-rounded",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-rounded.tsx")),
    files: [{
      path: "registry/examples/button-rounded.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-spinner": {
    name: "button-spinner",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-spinner.tsx")),
    files: [{
      path: "registry/examples/button-spinner.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-group-demo": {
    name: "button-group-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group"],
    component: lazy(() => import("~/registry/examples/button-group-demo.tsx")),
    files: [{
      path: "registry/examples/button-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "button-aschild": {
    name: "button-aschild",
    description: "",
    type: "registry:example",
    registryDependencies: ["button"],
    component: lazy(() => import("~/registry/examples/button-aschild.tsx")),
    files: [{
      path: "registry/examples/button-aschild.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "card-demo": {
    name: "card-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","card","input","label"],
    component: lazy(() => import("~/registry/examples/card-demo.tsx")),
    files: [{
      path: "registry/examples/card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "card-small": {
    name: "card-small",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","card"],
    component: lazy(() => import("~/registry/examples/card-small.tsx")),
    files: [{
      path: "registry/examples/card-small.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "card-image": {
    name: "card-image",
    description: "",
    type: "registry:example",
    registryDependencies: ["card"],
    component: lazy(() => import("~/registry/examples/card-image.tsx")),
    files: [{
      path: "registry/examples/card-image.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-demo": {
    name: "combobox-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-demo.tsx")),
    files: [{
      path: "registry/examples/combobox-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-basic": {
    name: "combobox-basic",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-basic.tsx")),
    files: [{
      path: "registry/examples/combobox-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-multiple": {
    name: "combobox-multiple",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-multiple.tsx")),
    files: [{
      path: "registry/examples/combobox-multiple.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-clear": {
    name: "combobox-clear",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-clear.tsx")),
    files: [{
      path: "registry/examples/combobox-clear.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-groups": {
    name: "combobox-groups",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-groups.tsx")),
    files: [{
      path: "registry/examples/combobox-groups.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-custom": {
    name: "combobox-custom",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-custom.tsx")),
    files: [{
      path: "registry/examples/combobox-custom.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-invalid": {
    name: "combobox-invalid",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-invalid.tsx")),
    files: [{
      path: "registry/examples/combobox-invalid.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-disabled": {
    name: "combobox-disabled",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-disabled.tsx")),
    files: [{
      path: "registry/examples/combobox-disabled.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-auto-highlight": {
    name: "combobox-auto-highlight",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-auto-highlight.tsx")),
    files: [{
      path: "registry/examples/combobox-auto-highlight.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-popup": {
    name: "combobox-popup",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox"],
    component: lazy(() => import("~/registry/examples/combobox-popup.tsx")),
    files: [{
      path: "registry/examples/combobox-popup.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "combobox-input-group": {
    name: "combobox-input-group",
    description: "",
    type: "registry:example",
    registryDependencies: ["combobox","input-group"],
    component: lazy(() => import("~/registry/examples/combobox-input-group.tsx")),
    files: [{
      path: "registry/examples/combobox-input-group.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command-demo": {
    name: "command-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["command"],
    component: lazy(() => import("~/registry/examples/command-demo.tsx")),
    files: [{
      path: "registry/examples/command-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command-basic": {
    name: "command-basic",
    description: "",
    type: "registry:example",
    registryDependencies: ["command","button"],
    component: lazy(() => import("~/registry/examples/command-basic.tsx")),
    files: [{
      path: "registry/examples/command-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command-shortcuts": {
    name: "command-shortcuts",
    description: "",
    type: "registry:example",
    registryDependencies: ["command","button"],
    component: lazy(() => import("~/registry/examples/command-shortcuts.tsx")),
    files: [{
      path: "registry/examples/command-shortcuts.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command-groups": {
    name: "command-groups",
    description: "",
    type: "registry:example",
    registryDependencies: ["command","button"],
    component: lazy(() => import("~/registry/examples/command-groups.tsx")),
    files: [{
      path: "registry/examples/command-groups.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "command-scrollable": {
    name: "command-scrollable",
    description: "",
    type: "registry:example",
    registryDependencies: ["command","button"],
    component: lazy(() => import("~/registry/examples/command-scrollable.tsx")),
    files: [{
      path: "registry/examples/command-scrollable.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "navigation-menu-demo": {
    name: "navigation-menu-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["navigation-menu"],
    component: lazy(() => import("~/registry/examples/navigation-menu-demo.tsx")),
    files: [{
      path: "registry/examples/navigation-menu-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "hover-card-demo": {
    name: "hover-card-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","hover-card"],
    component: lazy(() => import("~/registry/examples/hover-card-demo.tsx")),
    files: [{
      path: "registry/examples/hover-card-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "hover-card-sides": {
    name: "hover-card-sides",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","hover-card"],
    component: lazy(() => import("~/registry/examples/hover-card-sides.tsx")),
    files: [{
      path: "registry/examples/hover-card-sides.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-demo": {
    name: "input-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-demo.tsx")),
    files: [{
      path: "registry/examples/input-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-basic": {
    name: "input-basic",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-basic.tsx")),
    files: [{
      path: "registry/examples/input-basic.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-field": {
    name: "input-field",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-field.tsx")),
    files: [{
      path: "registry/examples/input-field.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-fieldgroup": {
    name: "input-fieldgroup",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-fieldgroup.tsx")),
    files: [{
      path: "registry/examples/input-fieldgroup.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-disabled": {
    name: "input-disabled",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-disabled.tsx")),
    files: [{
      path: "registry/examples/input-disabled.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-invalid": {
    name: "input-invalid",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-invalid.tsx")),
    files: [{
      path: "registry/examples/input-invalid.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-file": {
    name: "input-file",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-file.tsx")),
    files: [{
      path: "registry/examples/input-file.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-inline": {
    name: "input-inline",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-inline.tsx")),
    files: [{
      path: "registry/examples/input-inline.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-grid": {
    name: "input-grid",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-grid.tsx")),
    files: [{
      path: "registry/examples/input-grid.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-required": {
    name: "input-required",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-required.tsx")),
    files: [{
      path: "registry/examples/input-required.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-badge": {
    name: "input-badge",
    description: "",
    type: "registry:example",
    registryDependencies: ["input"],
    component: lazy(() => import("~/registry/examples/input-badge.tsx")),
    files: [{
      path: "registry/examples/input-badge.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-input-group": {
    name: "input-input-group",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-input-group.tsx")),
    files: [{
      path: "registry/examples/input-input-group.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-button-group": {
    name: "input-button-group",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","button-group","input"],
    component: lazy(() => import("~/registry/examples/input-button-group.tsx")),
    files: [{
      path: "registry/examples/input-button-group.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-form": {
    name: "input-form",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","input"],
    component: lazy(() => import("~/registry/examples/input-form.tsx")),
    files: [{
      path: "registry/examples/input-form.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "label-demo": {
    name: "label-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["label"],
    component: lazy(() => import("~/registry/examples/label-demo.tsx")),
    files: [{
      path: "registry/examples/label-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "field-demo": {
    name: "field-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input","label"],
    component: lazy(() => import("~/registry/examples/field-demo.tsx")),
    files: [{
      path: "registry/examples/field-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "separator-demo": {
    name: "separator-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["separator"],
    component: lazy(() => import("~/registry/examples/separator-demo.tsx")),
    files: [{
      path: "registry/examples/separator-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "separator-vertical": {
    name: "separator-vertical",
    description: "",
    type: "registry:example",
    registryDependencies: ["separator"],
    component: lazy(() => import("~/registry/examples/separator-vertical.tsx")),
    files: [{
      path: "registry/examples/separator-vertical.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "separator-menu": {
    name: "separator-menu",
    description: "",
    type: "registry:example",
    registryDependencies: ["separator"],
    component: lazy(() => import("~/registry/examples/separator-menu.tsx")),
    files: [{
      path: "registry/examples/separator-menu.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "separator-list": {
    name: "separator-list",
    description: "",
    type: "registry:example",
    registryDependencies: ["separator"],
    component: lazy(() => import("~/registry/examples/separator-list.tsx")),
    files: [{
      path: "registry/examples/separator-list.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-demo": {
    name: "input-group-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-demo.tsx")),
    files: [{
      path: "registry/examples/input-group-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-inline-start": {
    name: "input-group-inline-start",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-inline-start.tsx")),
    files: [{
      path: "registry/examples/input-group-inline-start.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-inline-end": {
    name: "input-group-inline-end",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-inline-end.tsx")),
    files: [{
      path: "registry/examples/input-group-inline-end.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-block-start": {
    name: "input-group-block-start",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-block-start.tsx")),
    files: [{
      path: "registry/examples/input-group-block-start.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-block-end": {
    name: "input-group-block-end",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-block-end.tsx")),
    files: [{
      path: "registry/examples/input-group-block-end.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-icon": {
    name: "input-group-icon",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-icon.tsx")),
    files: [{
      path: "registry/examples/input-group-icon.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-text": {
    name: "input-group-text",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-text.tsx")),
    files: [{
      path: "registry/examples/input-group-text.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-button": {
    name: "input-group-button",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group","popover"],
    component: lazy(() => import("~/registry/examples/input-group-button.tsx")),
    files: [{
      path: "registry/examples/input-group-button.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-kbd": {
    name: "input-group-kbd",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-kbd.tsx")),
    files: [{
      path: "registry/examples/input-group-kbd.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-dropdown": {
    name: "input-group-dropdown",
    description: "",
    type: "registry:example",
    registryDependencies: ["dropdown-menu","input-group"],
    component: lazy(() => import("~/registry/examples/input-group-dropdown.tsx")),
    files: [{
      path: "registry/examples/input-group-dropdown.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-spinner": {
    name: "input-group-spinner",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-spinner.tsx")),
    files: [{
      path: "registry/examples/input-group-spinner.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-textarea": {
    name: "input-group-textarea",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-textarea.tsx")),
    files: [{
      path: "registry/examples/input-group-textarea.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "input-group-custom": {
    name: "input-group-custom",
    description: "",
    type: "registry:example",
    registryDependencies: ["input-group"],
    component: lazy(() => import("~/registry/examples/input-group-custom.tsx")),
    files: [{
      path: "registry/examples/input-group-custom.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "textarea-demo": {
    name: "textarea-demo",
    description: "",
    type: "registry:example",
    registryDependencies: ["textarea"],
    component: lazy(() => import("~/registry/examples/textarea-demo.tsx")),
    files: [{
      path: "registry/examples/textarea-demo.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "textarea-field": {
    name: "textarea-field",
    description: "",
    type: "registry:example",
    registryDependencies: ["textarea"],
    component: lazy(() => import("~/registry/examples/textarea-field.tsx")),
    files: [{
      path: "registry/examples/textarea-field.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "textarea-disabled": {
    name: "textarea-disabled",
    description: "",
    type: "registry:example",
    registryDependencies: ["textarea"],
    component: lazy(() => import("~/registry/examples/textarea-disabled.tsx")),
    files: [{
      path: "registry/examples/textarea-disabled.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "textarea-invalid": {
    name: "textarea-invalid",
    description: "",
    type: "registry:example",
    registryDependencies: ["textarea"],
    component: lazy(() => import("~/registry/examples/textarea-invalid.tsx")),
    files: [{
      path: "registry/examples/textarea-invalid.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "textarea-button": {
    name: "textarea-button",
    description: "",
    type: "registry:example",
    registryDependencies: ["button","textarea"],
    component: lazy(() => import("~/registry/examples/textarea-button.tsx")),
    files: [{
      path: "registry/examples/textarea-button.tsx",
      type: "registry:example",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
  "use-mobile": {
    name: "use-mobile",
    description: "",
    type: "registry:hook",
    registryDependencies: undefined,
    component: lazy(() => import("~/registry/hooks/use-mobile.ts")),
    files: [{
      path: "registry/hooks/use-mobile.ts",
      type: "registry:hook",
      target: ""
    }],
    categories: undefined,
    meta: undefined,
  },
}
